server:
  port: ${ADDRESS_SERVER_PORT:8443}
  ssl:
    enabled: ${ADDRESS_SSL_ENABLED:true}
    key-store: classpath:keystore.p12
    key-store-password: ${ADDRESS_SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: address-service

spring:
  application:
    name: address-service

  datasource:
    url: jdbc:postgresql://localhost:5432/drugstore_addresses
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: false
    encoding: UTF-8
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:15}
  refresh-token-expiration-minutes: ${JWT_REFRESH_TOKEN_EXPIRATION_MINUTES:43200} # 30 days
  issuer: ${ISSUER}

app:
  rate-limit:
    global:
      enabled: true
      maxRequests: 5000
      durationHours: 1
    profiles:
      standard:
        maxRequests: 40
        durationSeconds: 60
      sensitive:
        maxRequests: 7
        durationSeconds: 60
      public:
        maxRequests: 100
        durationSeconds: 60
      admin:
        maxRequests: 50
        durationSeconds: 1
      customer-write:
        maxRequests: 20
        durationSeconds: 60
      customer-read:
        maxRequests: 100
        durationSeconds: 60

logging:
  file:
    name: logs/address-service.log
    path: logs
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    io.github.alexisTrejo11.drugstore: DEBUG
    libs_kernel.log.audit: INFO

audit:
  log:
    enabled: true
    excluded-endpoints: >
      /actuator/health,
      /actuator/info,
      /swagger-ui.html,
      /v3/api-docs