server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info

spring:
  application:
    name: spring-boot-admin
  boot:
    admin:
      discovery:
        enabled: true

      client:
        instance:
          prefer-ip: true
          service-base-url: https://localhost:8443
          management-base-url: https://localhost:8443/actuator

