spring:
  application:
    name: order-service

  # Postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/drugstore_orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    schemas: public
    clean-disabled: false


server:
  port: 8080