# Service Name
spring.application.name=product-service

# Port
server.port=8085

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# Spring Boot Admin Client Configuration
spring.boot.admin.client.url=http://localhost:8081

# Health Check Configuration
management.endpoints.web.exposure.include=*

# Enable Eureka Client
spring.cloud.netflix.eureka.client.enabled=true

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/drugstore
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Migration
spring.jpa.hibernate.ddl-auto=update

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.paths-to-match=/**
springdoc.packages-to-scan=microservice.product_service

# Cache
spring.cache.type=caffeine

# Configure specific caches
spring.cache.cache-names=allProducts,products,product,productsBySupplier,productsByCategory,productsBySubcategory
spring.cache.caffeine.spec=maximumSize=100,expireAfterAccess=600s

logging.level.org.springframework.cache=DEBUG

spring.main.lazy-initialization=true
spring.datasource.hikari.maximum-pool-size=20
server.tomcat.max-threads=200

