services:
  postgres:
    image: postgres:15-alpine
    container_name: drugstore_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drugstore_users
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - drugstore-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: drugstore_redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      - drugstore-network
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway:9.22.0
    depends_on:
      postgres:
        condition: service_healthy
    command: -url=jdbc:postgresql://postgres:5432/drugstore_users -user=postgres -password=root -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - drugstore-network

volumes:
  postgres_data:
  redis_data:


networks:
  drugstore-network:
    driver: bridge
